# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(319, 226)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.time_label = QtWidgets.QLabel(self.frame)
        self.time_label.setStyleSheet("color: #00FF00")
        self.time_label.setObjectName("time_label")
        self.verticalLayout.addWidget(self.time_label)
        self.two_hours_button = QtWidgets.QPushButton(self.frame)
        self.two_hours_button.setAutoDefault(True)
        self.two_hours_button.setObjectName("two_hours_button")
        self.verticalLayout.addWidget(self.two_hours_button)
        self.one_hour_button = QtWidgets.QPushButton(self.frame)
        self.one_hour_button.setAutoDefault(True)
        self.one_hour_button.setObjectName("one_hour_button")
        self.verticalLayout.addWidget(self.one_hour_button)
        "TEST"
        self.thirty_one_min_button = QtWidgets.QPushButton(self.frame)
        self.thirty_one_min_button.setAutoDefault(True)
        self.thirty_one_min_button.setObjectName("thirty_one_min_button")
        self.verticalLayout.addWidget(self.thirty_one_min_button)
        self.one_min_button = QtWidgets.QPushButton(self.frame)
        self.one_min_button.setAutoDefault(True)
        self.one_min_button.setObjectName("one_min_button")
        self.verticalLayout.addWidget(self.one_min_button)
        "TEST"
        self.thirty_min_button = QtWidgets.QPushButton(self.frame)
        self.thirty_min_button.setAutoDefault(True)
        self.thirty_min_button.setObjectName("thirty_min_button")
        self.verticalLayout.addWidget(self.thirty_min_button)
        self.cancel_button = QtWidgets.QPushButton(self.frame)
        self.cancel_button.setAutoDefault(True)
        self.cancel_button.setObjectName("cancel_button")
        self.verticalLayout.addWidget(self.cancel_button)
        self.exit_button = QtWidgets.QPushButton(self.frame)
        self.exit_button.setAutoDefault(True)
        self.exit_button.setObjectName("exit_button")
        self.verticalLayout.addWidget(self.exit_button)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 319, 20))
        self.menubar.setObjectName("menubar")
        self.menuMen = QtWidgets.QMenu(self.menubar)
        self.menuMen.setObjectName("menuMen")
        MainWindow.setMenuBar(self.menubar)
        self.action_Dark_Mode = QtWidgets.QAction(MainWindow)
        self.action_Dark_Mode.setObjectName("action_Dark_Mode")
        self.action_Beenden = QtWidgets.QAction(MainWindow)
        self.action_Beenden.setObjectName("action_Beenden")
        self.action_Light_Mode = QtWidgets.QAction(MainWindow)
        self.action_Light_Mode.setObjectName("action_Light_Mode")
        self.menuMen.addAction(self.action_Dark_Mode)
        self.menuMen.addAction(self.action_Light_Mode)
        self.menuMen.addAction(self.action_Beenden)
        self.menubar.addAction(self.menuMen.menuAction())

        self.retranslateUi(MainWindow)
        self.exit_button.clicked.connect(MainWindow.close) # type: ignore
        self.action_Beenden.triggered.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.time_label.setText(_translate("MainWindow", "The system will shut down in:"))
        self.two_hours_button.setText(_translate("MainWindow", "2 hours"))
        self.one_hour_button.setText(_translate("MainWindow", "1 hour"))
        "TEST"
        self.thirty_one_min_button.setText(_translate("MainWindow", "31 mins"))
        self.thirty_one_min_button.setText(_translate("MainWindow", "1 mins"))
        "TEST"
        self.thirty_min_button.setText(_translate("MainWindow", "30 minutes"))
        self.cancel_button.setText(_translate("MainWindow", "Reset the timer"))
        self.exit_button.setText(_translate("MainWindow", "Exit"))
        self.menuMen.setTitle(_translate("MainWindow", "Menü"))
        self.action_Dark_Mode.setText(_translate("MainWindow", "Dark Mode"))
        self.action_Beenden.setText(_translate("MainWindow", "Quit"))
        self.action_Light_Mode.setText(_translate("MainWindow", "Light Mode"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
